src/Entity/Places.php
<?php

namespace App\Entity;

use App\Repository\PlacesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Vich\UploaderBundle\Entity\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Validator\Constraints\ImageValidator;

/**
 * @ORM\Entity(repositoryClass=PlacesRepository::class)
 * @Vich\Uploadable()
 */
class Places
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $commune;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $start_point;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $interest_point;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 30,
     *      notInRangeMessage = "La distance si vous l'indiquez doit être comprise entre {{ min }} et {{ max }} km",
     * )
     */
    private $distance;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 300,
     *      notInRangeMessage = "Le temps si vous l'indiquez doit être compris entre {{ min }} et {{ max }} minutes",
     * )
     */
    private $time;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\ExpressionLanguageSyntax(allowedVariables={"balade", "autre"},message="type balade ou autre si pas de marche")
     */
    private $type;

    /**
     *
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="place")
     */
    private $comments;

     /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="place")
     */
    private $images;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $difficulty;

    /**
     * @Vich\UploadableField(mapping="places", fileNameProperty="imagename")
     * @var File
     * @Assert\Image(
     *     maxWidth = 1600,
     *  )
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imagename;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */

    private $updatedat;

    /**
     * @ORM\Column(type="boolean")
     */
    private $published;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCommune(): ?string
    {
        return $this->commune;
    }

    public function setCommune(string $commune): self
    {
        $this->commune = $commune;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartPoint(): ?string
    {
        return $this->start_point;
    }

    public function setStartPoint(string $start_point): self
    {
        $this->start_point = $start_point;

        return $this;
    }

    public function getInterestPoint(): ?string
    {
        return $this->interest_point;
    }

    public function setInterestPoint(string $interest_point): self
    {
        $this->interest_point = $interest_point;

        return $this;
    }

    public function getDistance(): ?int
    {
        return $this->distance;
    }

    public function setDistance(?int $distance): self
    {
        $this->distance = $distance;

        return $this;
    }

    public function getTime(): ?int
    {
        return $this->time;
    }

    public function setTime(?int $time): self
    {
        $this->time = $time;

        return $this;
    }
    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPlace($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPlace() === $this) {
                $comment->setPlace(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setPlace($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getPlace() === $this) {
                $image->setPlace(null);
            }
        }

        return $this;
    }

    public function getDifficulty(): ?string
    {
        return $this->difficulty;
    }

    public function setDifficulty(?string $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedat;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getimageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile($image):void
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageName(): ?string
    {
        return $this->imagename;
    }

    public function setImageName (?string $imagename): self
    {
        $this->imagename = $imagename;

        return $this;
    }

    public function getPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }
    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('time', new Assert\Positive());
    }
}

src/Controller/PlacesController.php
<?php

namespace App\Controller;

use App\Entity\Places;
use App\Entity\Comments;
use App\Entity\User;
use App\Form\PlacesType;
use App\Form\CommentType;
use App\Form\CommenType;
use App\Repository\PlacesRepository;
use Doctrine\ORM\EntityManagerInterface;
use PhpParser\Node\Stmt\Foreach_;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\DateTime;
use Vich\UploaderBundle\Entity\File;

/**
 * @Route("/balades")
 */
class PlacesController extends AbstractController
{
    /**
     * @Route("/", name="baladesListe", methods={"GET"})
     */
    public function index(PlacesRepository $placesRepository): Response
    {
        /**
         * affiche tous les lieux enregistrés en bdd triées par type (autre/balade)
         * puis par commune
         */
        return $this->render('places/index.html.twig', [
            'places' => $placesRepository->sortFindAll(),
        ]);
    }
    /**
     * @Route("/listeBalades", name="listeBalades", methods={"GET"})
     */
    public function listPlaces(PlacesRepository $placesRepository): Response
    {
        /**
         * affiche toutes les balades enregistrés en bdd triées par commune
         */
        return $this->render('places/indexPlaces.html.twig', [
            'places' => $placesRepository->FindAllPlaces('balade'),
        ]);
    }
    /**
     * @Route("/listeAutres", name="listeAutres", methods={"GET"})
     */
    public function listOthers(PlacesRepository $placesRepository): Response
    {
        /**
         * affiche tous les autres lieux à voir enregistrés en bdd tries par commune
         */
        return $this->render('places/indexOthers.html.twig', [
            'places' => $placesRepository->FindAllPlaces('autre'),
        ]);
    }

    /**
     * @Route("/{id}", name="baladesAfficher", methods={"GET"})
     */
    public function show(Places $place): Response
    {
        /**
         * appel de la vue qui affiche le détail du lieu par son id
         */
        return $this->render('places/show.html.twig', [
            'place' => $place,
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/{id}/edit", name="baladesModifier", methods={"GET","POST"})
     */
    public function edit(Request $request, Places $place): Response
    {
        /**
         * fonction réservée à l'admin qui récupère les données modifiées pour un lieu
         * et les enregistre en BDD
         */
        $form = $this->createForm(PlacesType::class, $place);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $published = $form['published']->getData();
            if ($published) {
                $place->setPublished(true) ;
             }
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('baladesListe');
        }

        return $this->render('places/edit.html.twig', [
            'place' => $place,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/{id}/delete", name="baladesSupprimer", methods={"DELETE"})
     */
    public function delete(Request $request, Places $place): Response
    {
        /**
         * fonction réservée à l'admin qui supprime un lieu de la BDD après confirmation
        */
        if ($this->isCsrfTokenValid('delete'.$place->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($place);
            $entityManager->flush();
        }

        return $this->redirectToRoute('baladesListe');
    }
    /**
     * @IsGranted("ROLE_MEMBER")
     * @Route("/envoyerCommentaire/{id}", name="envoyerCommentaire", methods={"GET","POST"})
     */
    public function sendComment(Request $request, Places $place, MailerInterface $mailer): Response
    {
        $form = $this->createForm(CommentType::class);
        $form->handleRequest($request);
        $user = $this->getUser();
        $usermail = $user->getUsername();
        if ($form->isSubmitted() && $form->isValid()) {
            /**
             *  On récupère les données transmises : le lieu sélectionné, l'utilisateur qui envoie
             *  le commentaire et le texte du commentaire saisi dans le formulaire
             */

            $placetitle= $place->getTitle();
            $comment = $form->get('commentaire')->getData();
            /**
             * préparation du mail avec le format préparé
             */
            $mail=(new TemplatedEmail())
                ->to ('myriam.trillat.simplon@gmail.com')
                ->from ($usermail)
                ->subject('Envoi commentaire')
                ->htmlTemplate('places/email.html.twig')
                // on passe les variables au template
                ->context([
                    'titrebalade' => $placetitle,
                    'mailexp' => $usermail,
                    'commentaire'=> $comment
                ])
            ;
            /**
             * envoie du mail et affichage d'un message de succès
             */
            $mailer->send($mail);
            if (!$this->isGranted("ROLE_ADMIN")) {
                $this->addFlash('message', 'Commentaire envoyé par mail avec succès');
            }
            return $this->redirectToRoute("baladesListe");
        }
        return $this->render('places/sendComment.html.twig', [
            'place' => $place,
            'form' => $form->createView()
        ]);
    }
    /**
     * @IsGranted("ROLE_MEMBER")
     * @Route("/baladesProposer/{user}", name="baladesProposer", methods={"GET","POST"})
     *
     */
    public function proposePlace(Request $request, User  $user, MailerInterface $mailer): Response
    {
        /**
         * instanciation d'une nouvelle class Places et appel du formulaire de saisie
         * créé à partir du modèle de la classe Places
         */
        $place = new Places();
        $form = $this->createForm(PlacesType::class, $place);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $place->setPublished(false);
            /**
             * si les données saisies pour ajouter un nouveau lieu sont correctes,
             * affectation des données à la nouvelle instanciation de classe
             * par défaut l'état publié est à false
             */
                if ($this->isGranted("ROLE_ADMIN")){
                    /**
                     * pour le role admin, l'état publié est à true pour afficher directement ce lieu
                     */
                    $place->setPublished(true);
                }
            /**
             * les données sont prêtes à être enregistrées
             */
            $entityManager->persist($place);
            /**
             * les données sont enregistrées dans la bdd
             */
            $entityManager->flush();

            if (!$this->isGranted("ROLE_ADMIN")) {
                /**
                 *  Si c'est juste un utilisateur de role membre qui propose un nouveau lieu,
                 * on récupère les données transmises dans le formulaire pour envoyer un mail
                 * à l'admin
                 */

                $mailexp = $user->getEmail();
                $placetitle = $form->get('title')->getData();
                $commune = $form->get('commune')->getData();
                $description = $form->get('description')->getData();
                $type = $form->get('type')->getData();
                $time = $form->get('time')->getData();
                $depart = $form->get('start_point')->getData();
                $interest = $form->get('interest_point')->getData();
                $distance = $form->get('distance')->getData();
                $difficulty = $form->get('difficulty')->getData();
                /**
                 * utilisation d'un template de formatage du mail
                 */
                $mail = (new TemplatedEmail())
                    ->to('myriam.trillat.simplon@gmail.com')
                    ->from($mailexp)
                    ->subject('Envoi balade')
                    ->htmlTemplate('places/emailPlace.html.twig')
                    ->context([
                        'mailexp' => $mailexp,
                        'titrebalade' => $placetitle,
                        'commune' => $commune,
                        'description' => $description,
                        'depart' => $depart,
                        'interet' => $interest,
                        'temps' => $time,
                        'distance' => $distance,
                        'type' => $type,
                        'difficulte' => $difficulty

                    ]);
                /**
                 * envoi du mail préparé via la fonction send
                 */
                $mailer->send($mail);
                /**
                 * affichage d'un message de bon envoi du mail à l'utilisateur
                 */
                $this->addFlash("message", "Votre balade a bien été enregistrée, elle sera publiée après contrôle");

            }
            /**
             * après l'ajout d'une balade, on revient sur la liste complète des lieux
             */
            return $this->redirectToRoute('baladesListe');
        }

        return $this->render('places/new.html.twig', [
            'place' => $place,
            'form' => $form->createView(),

templates/places/deleteForm.html.twig
<form method="post" action="{{ path('baladesSupprimer', {'id': place.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ place.id) }}">
    <button class="btn btn-outline-primary">Supprimer</button>
</form>

templates/places/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Monjoligrési - Edit Balades{% endblock %}

{% block main %}
    <div class="container">

        <h1 class="text-center">Modification d'une Balade</h1>

        {{ include('places/form.html.twig') }}

        <div class="row justify-content-center">

             {{ include('places/deleteForm.html.twig') }}

        </div>

    </div>
{% endblock %}

templates/places/emailPlace.html.twig
{% block main %}
<h2 style="text-align: center">Nouvelle suggestion de balade</h2>
    <p style="margin-left: auto">mail expéditeur : {{ mailexp }}</p>
    <p style="margin-left: auto">balade titre: {{ titrebalade }}</p>
    <p style="margin-left: auto">commune : {{ commune }}</p>
    <p style="margin-left: auto">description : {{ description }}</p>
    <p style="margin-left: auto">point de départ : {{ depart }}</p>
    <p style="margin-left: auto">point d interet : {{ interet }}</p>
    <p style="margin-left: auto">distance : {{ distance }}</p>
    <p style="margin-left: auto">temps : {{ temps }}</p>
    <p style="margin-left: auto">type : {{ type }}</p>
    <p style="margin-left: auto">difficulte : {{ difficulte }}</p>

{% endblock %}

templates/places/form.html.twig
{{ form_start(form) }}

  {% if is_granted('ROLE_ADMIN') %}
     {{ form_row(form.published,{'label': '  publié'}) }}
  {% else %}
      {{ form_row(form.published,{'attr': {'class': 'notpublished'}, 'label': false}) }}
  {% endif %}
{#  {{ form_row(form.type,{'label': '  publié'}) }}#}
 {{ form_rest(form) }}

    <div class="row justify-content-center ">
    <button class="mr-2 btn btn-outline-primary">{{ button_label|default('Enregistrer') }}</button>
    <a class="ml-2 btn btn-outline-primary text-center" href="{{ path('baladesListe') }}">Retour liste</a>
    </div>
{{ form_end(form) }}

templates/places/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Monjoligrési - toutes les balades{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('print') }}
{% endblock %}
{% block main %}
    <div class="container">
        {# affichage d'un message s'il y en a   #}
        {% for message in app.flashes('message') %}
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                <div class="flash-notice">
                    <h5 class="alert-heading">Bravo ! </h5>
                    <p>{{ message }}</p>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {# flash-notice #}
            </div>
            {# alert #}
        {% endfor %}
        <div class="text-center row">
            <div class="col">
                <a class="noprint btn btn-outline-primary text-center mb-2" href="{{ path('listeBalades') }}">Que les balades</a>
             </div>
            {% if is_granted('ROLE_MEMBER') %}
                <div class="col">
                    <a class="noprint btn btn-outline-primary text-center mb-2" href="{{ path('baladesProposer', {'user': app.user.id} ) }}">Proposer une balade</a>
                </div>
            {% endif %}
             <div class="col">
              <a class="noprint btn btn-outline-primary text-center mb-2" href="{{ path('listeAutres') }}">Autres lieux</a>
             </div>
        </div>

    <table class="table">
        <tbody>
       {% set cptb = 0 %}
       {% set cpta = 0 %}
        {% for place in places %}
            {% if (place.published) or (not place.published and is_granted('ROLE_ADMIN'))%}
                {# affichage des balades publiées pour les membres ou toutes si user admin #}
            <div class="text-center card">
                <div class="card-body">
                    {# on affiche d'abord les places puis les autres lieux à voir  #}

                    {% if place.type  == 'balade' and cptb == 0 %}
                        <h3>Les balades </h3>
                        {% set cptb = 1 %}
                    {% endif %}
                    {% if place.type  == 'autre' and cpta == 0 %}
                        <h3>Autres lieux à voir </h3>
                        {% set cpta = 1 %}
                    {% endif %}
                    <h4 class="card-title">{{ place.title }}</h4>
                    <p class="card-text">Description : {{ place.description }}</p>
                    <p class="card-text">Commune : {{ place.commune }}</p>
                    {% if place.interestPoint  %}
                        <p class="card-text">Points d'intérêts : {{  place.interestPoint }} </p>
                    {% endif %}
                     {% if place.imagename %}
                        <p class="card-text"><img class="photo" src="{{ vich_uploader_asset(place,'imageFile')}}" alt="{{  place.imagename }}"></p>
                    {% endif %}
                     {% if is_granted('ROLE_ADMIN') %}
                         {# affichage de l'état de la balade si role admin #}
                        {% if place.published  %}
                            <p class="card-text">balade publiée</p>
                        {% else %}
                            <p class="btn btn-secondary card-text">balade non publiée</p>
                        {% endif %}
                    {% endif %}
                    <div class="row mt-1">
                        <div class="col">
                            <div><a href="#"><figure><img class="noprint btnPrint icon__social" src="{{ asset('build/print.png') }}" alt="icone print" title=""></figure></a>
                            </div>
                        </div>
                        <div class="col">
                            <div><a class="noprint btn btn-outline-primary" href="{{ path('baladesAfficher', {'id': place.id}) }}">Détail</a>
                            </div>
                        </div>

                        {% if is_granted('ROLE_MEMBER') %}
                            <div class="col">
                                <a class="noprint btn btn-outline-primary" href="{{ path('ajoutCommentaire', {'id': place.id}) }}">Ajouter un commentaire</a>
                            </div>
                        {% endif %}
                      {#  <div class="col"> icone like prévu pour une version ultérieure
                            <a href="#"><figure><img class="icon__social colBlue" src="{{ asset('build/like.png') }}" alt="location" title=""></figure></a>
                        </div>#}

                    </div>
                    {# #fin ligne icones #}
                    <div class="row mt-2">

                        {% if is_granted('ROLE_ADMIN') %}
                           <div class="col">
                              <div><a class="btn btn-outline-primary" href="{{ path('baladesModifier', {'id': place.id}) }}">Modifier</a>                          </div>
                            </div>
                            <div class="col colBlue ">
                                {{ include('places/deleteForm.html.twig') }}
                            </div>
                        {% endif %}
                    </div>
                </div> {# fin card body #}
            </div> {# fin div text center #}
            {% endif %} {# fin if publie=true, balade affichée #}
        {% else %}
            {# #fin si table places vide #}
            <tr>
                <td class="text-center mt-2" colspan="9">Pas de balade !</td>
            </tr>
        {% endfor %} {# fin boucle sur places #}

        </tbody>
    </table>

    </div>
{% endblock %}
 {% block javascripts %}
     {{ encore_entry_script_tags('places') }}
     {{ encore_entry_script_tags('print') }}
 {% endblock %}

templates/places/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Monjoligrési - ajouter balade{% endblock %}

{% block main %}
    <div class="container">
        <h1 class="text-center">Ajouter une balade</h1>
        {% if not is_granted('ROLE_ADMIN') %}
             <p class="text-center alert-info">Cette balade sera effectivement publiée après validation</p>
        {%  endif %}

        <p class="text-center"></p>

        {{ include('places/form.html.twig') }}

    </div>
{% endblock %}

templates/places/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Monjoligrési - détail{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('print') }}
{% endblock %}

{% block main %}
    <div class="text-center card border-primary">
    {#affichage du détail d'un lieu#}
        <div class="card-body">
{#          affichage du titre selon le type du lieu,           #}
            {% if place.type  == 'balade'%}
                <h3>Balade </h3>
            {% endif %}
            {% if place.type  == 'autre' %}
                <h3>Autre lieu à voir </h3>
            {% endif %}
            <h4 class="card-title">{{ place.title }}</h4>
{#            Si le lieu est une balade on affiche la distance et le temps si remplis#}
            {% if place.type  == 'balade' %}
                <div class="row justify-content-around">
                    {% if place.distance is not null  %}
                    <p class="mr-2 card-text align-content-center">Distance: {{  place.distance }} km</p>
                    {% endif %}
                    {% if place.time is not null %}
                    <p class="ml-2 card-text align-content-center">Temps: {{ place.time }} min </p>
                    {% endif %}
                </div>
                 {% if place.difficulty is not null  %}
                    <p class="card-text">Difficulté : {{  place.difficulty }} </p>
                 {% endif %}
            {% endif %}
            <!--<p class="card-text" style="color:#B01377">Distance &nbsp : &nbsp ${res[i].distance}Km &nbsp | &nbsp Temps &nbsp : &nbsp ${formattedTime}</p>-->
            <p class="card-text">Description : {{ place.description }}</p>
            <p class="card-text">Commune : {{ place.commune }}</p>
            <p class="card-text">Point de départ : {{ place.startPoint }}</p>
            {% if place.interestPoint %}
              <p class="card-text">Points d'intérêts : {{  place.interestPoint }} </p>
            {% endif %}
            {% if place.imagename %}
                <p class="card-img-top"><img class="photo" src="{{ vich_uploader_asset(place,'imageFile')}}" alt="{{  place.imagename }}"></p>
            {% endif %}

            <div class="row">
                <div class="col">
                    <div><a href="#"><img class="noprint btnPrint icon__social" src="{{ asset('build/print.png') }}" alt="print" title=""></a>
                    </div>
                </div>
                <div class="col">
                    <a class="noprint btn btn-outline-primary" href="{{ path('baladesListe') }}">Retour liste</a>
                </div>

                {% if is_granted('ROLE_MEMBER') %}
{#                    un utilisateur connecté peut envoyer un commentaire#}
                    <div class="col">
                        <a class="noprint btn btn-outline-primary" href="{{ path('ajoutCommentaire', {'id': place.id}) }}">Ajouter un commentaire</a>
                    </div>
                {% endif %}
              {#  <div class="col">
                    <a class="colBlue" href="#"><figure><img id="btnLocation" class="icon__social " src="{{ asset('build/location.png') }}" alt="location" title=""></figure></a>
                </div>#}
            </div>
            <div class="row mt-2">

                {% if is_granted('ROLE_ADMIN') %}
{#                    ajout d'actions possible pour l'utilisateur admin : #}
{#                    modifier ou  supprimer le lieu#}

                    <div class="col">
                        <div><a class="btn btn-outline-primary" href="{{ path('baladesModifier', {'id': place.id}) }}">Modifier</a></div>
                    </div>
                    <div class="col">
                        {{ include('places/deleteForm.html.twig') }}
                    </div>
                {% endif %}
            </div>
            <div class="row">
                <h4 class="col mt-2 text-center">Commentaires</h4>
            </div>
                {% for comment in place.comments %}
                    {% if comment.published or is_granted('ROLE_ADMIN') %}
                        <hr>
                    {% endif %}
                    {#on boucle sur les commentaires liés à cette balade#}
                   <div class="row">
                       {% if comment.published or is_granted('ROLE_ADMIN') %}
                           <hr>
                            <div class="col text-center">{{ comment.textcomment }}</div>
                       {% endif %}
                        {% if is_granted('ROLE_ADMIN') %}

{#                        l'admin peut publier ou supprimer le commentaire affiché#}
                         <div class="col text-center">  {{ include('comments/deleteForm.html.twig') }}</div>
                        {% if not comment.published  %}
                            <div class="col text-center"> <a class="noprint btn btn-outline-primary" href="{{ path('publishComment', {'id': comment.id}) }}">publier</a> </div>
                            <p class="btn btn-secondary card-text">commentaire non publié</p>
                        {% endif %}
                    {% endif %}
                   </div>
                {% endfor %}
        </div>
    </div>

{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('places') }}
    {{ encore_entry_script_tags('print') }}
{% endblock %}